### ISSUE TITLE
TemplateSyntaxError when using {% get_metadata %}

### ISSUE THREAD

**Issue by dzida** [willhardy/django-seo#14]
Hi again,

I have a problem with get_metadata tag, my template's fragment looks like this:
    {% load seo %}
    {% get_metadata as seo_data %}
    {{seo_data.keywords}}

On my dev box it works fine, but on test server it raises an error:

```
File "/usr/local/lib/python2.6/dist-packages/Django_SEO-1.0beta1-py2.6.egg/rollyourown/seo/templatetags/seo.py", line 31, in render
raise template.TemplateSyntaxError(msg)

TemplateSyntaxError: {% get_metadata %} needs some path information.
Please use RequestContext with the django.core.context_processors.request context processor.
Or provide a path or object explicitly, eg {% get_metadata for path %} or {% get_metadata for object %}
```

Any ideas what is wrong?

**Comment by willhardy** [comment]
Are you passing `RequestContext` to your template?

**Comment by dzida** [comment]
Yes, I always pass RequestContext (I use following pattern in all my views: **return render_to_response('name.html', {...}, context_instance=RequestContext(request))**)

**Comment by willhardy** [comment]
That is odd, and can you confirm that you are using the following context processor:

`django.core.context_processors.request`

If you are, can you tell me which version of Django you are currently using?

**Comment by willhardy** [comment]
I've changed the way the path is discovered in the templatetag, try it out on your test server and let me know how it goes.

Cheers,

Will

**Comment by willhardy** [comment]
Closing this ticket, I believe the last change would have fixed any issues with access to the path. Please reopen if you're still getting an exception.

**Comment by dzida** [comment]
Yes, now it works fine.
Thanks a lot.
