### ISSUE TITLE
documentation template context processor

### ISSUE THREAD

**Issue by blite** [willhardy/django-seo#21]
I had to add the following to get django-seo to work maybe i'm using an older settings.py file though

TEMPLATE_CONTEXT_PROCESSORS = (
  "django.core.context_processors.request",

  "django.core.context_processors.auth",

  "django.core.context_processors.debug",

  "django.core.context_processors.i18n",

)    

it really only needs the first one but it should be in documentation I think.

**Comment by willhardy** [comment]
This isn't absolutely necessary, but I see the value in putting it in the tutorial. I'll add it now.

Thanks

**Comment by willhardy** [comment]
Closed by 3512c00d85a252adef09671156ba58dc9a9d174a: Adding the request context processor will make life easier.
