### ISSUE TITLE
Error on syncdb: AttributeError: 'tuple' object has no attribute 'index'

### ISSUE THREAD

**Issue by dzida** [willhardy/django-seo#4]
Hi,

I have a problem with running syncdb after installing django-seo (I use version from commit: https://github.com/willhardy/django-seo/commit/bce453c4c6c0d0fd71ab90881c2bd044cd87dc15)

Fragment of traceback:
  File "build\bdist.win32\egg\rollyourown\seo\base.py", line 202, in **new**
  File "build\bdist.win32\egg\rollyourown\seo\backends.py", line 309, in validate
AttributeError: 'tuple' object has no attribute 'index'

Before syncdb I have:
- installed django-seo
- added 'rollyourown.seo' to installed apps
- created seo.py with class which inherits MetaData
- added register_seo_admin call in admin.py file in my app

Any help is much appreciated.

Regards,
Lukasz

**Comment by willhardy** [comment]
Looks like I didn't test in python 2.5, as the `index` method for `tuple`s was first added in python 2.6 (ie 3k).

I've just pushed a fix for this, thanks for letting me know!

**Comment by dzida** [comment]
Now it works fine.

Thanks a lot!
